const LOAD_USERS = 'LOAD_USERS';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_COMMENTS = 'LOAD_COMMENTS';
const CHOOSER = 'CHOOSER';

export {
    LOAD_COMMENTS,
    LOAD_POSTS,
    LOAD_USERS,
    CHOOSER
}